name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment To Hugging Face
        env:
          HUGGING_FACE: ${{ secrets.HUGGING_FACE }}
        run: make deploy HUGGING_FACE=$HUGGING_FACE